/*
 * Partial Drawbridge header
 *
 * This will be completed as required within the context of my work.
 *
 */

DKSTATUS VirtualMemoryAllocate(PVOID, SIZE_T, DK_ALLOCATION_TYPE, DK_PAGE_PROTECTION, PVOID *, PSIZE_T)
DKSTATUS VirtualMemoryFree(PVOID, SIZE_T, DK_FREE_TYPE)
DKSTATUS VirtualMemoryProtect(PVOID, SIZE_T, DK_PAGE_PROTECTION, PDK_PAGE_PROTECTION)
DKSTATUS SemaphoreRelease(DKHANDLE, LONG)
DKSTATUS AsyncPoll(DKHANDLE, PDK_ASYNC_RESULTS)
DKSTATUS StreamSetLength(DKHANDLE, ULONG64)
DKSTATUS StreamFlush(DKHANDLE)
DKSTATUS StreamDelete(DKHANDLE)
DKSTATUS StreamGetEvent(DKHANDLE, DK_STREAM_EVENT_ID, PDKHANDLE)
DKSTATUS StreamRename(DKHANDLE, const UNICODE_STRING *)
DKSTATUS StreamMap(DKHANDLE, PVOID, DK_STREAM_MAP_FLAGS, DK_PAGE_PROTECTION, ULONG64, PSIZE_T, PSIZE_T, PVOID *)
DKSTATUS StreamMapPeBinary(DKHANDLE, PVOID, DK_STREAM_MAP_FLAGS, PSIZE_T, PVOID *)
DKSTATUS StreamUnmap(PVOID)
DKSTATUS StreamEnumerateChildren(DKHANDLE, PDKHANDLE, PUNICODE_STRING)
DKSTATUS ThreadSetRegisters(const DK_THREAD_REGISTER_VALUES *)
DKSTATUS ThreadCreate(PLIBOS_ThreadStart, PVOID, PVOID, const DK_THREAD_CREATE_PARAMETERS *, PDKHANDLE)
DKSTATUS ProcessCreate(const DK_PROCESS_CREATE_PARAMETERS *, PDKHANDLE, PDKHANDLE)
DKSTATUS SystemTimeQuery(PLONG64)
DKSTATUS StreamRangeLock(DKHANDLE, ULONG64, ULONG64, BOOLEAN, BOOLEAN, PDKHANDLE)
DKSTATUS StreamEnableSparse(DKHANDLE, BOOLEAN)
DKSTATUS StreamQueryAllocatedRanges(DKHANDLE, const DK_FILE_RANGE *, ULONG, PDK_FILE_RANGE, PULONG)
DKSTATUS StreamSetZeroData(DKHANDLE, const DK_FILE_RANGE *)
DKSTATUS CommitMemory(PVOID, SIZE_T, DK_PAGE_PROTECTION)
DKSTATUS StreamOpen(PDKHANDLE, const char *, DK_ACCESS_MASK, DK_STREAM_OPEN_DISPOSITION, DK_STREAM_OPEN_OPTIONS)

